language: ruby
rvm:
    - "1.9.3"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: latest
script: PADRINO_ENV=test padrino rake
bundler_args: --without development production
